title: learning english
author: gzc
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  happy learning english

# social links
twitter_username: gzc
github_username:  gzc

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
